In [2]:
import tensorflow as tf

INITIALIZATION TENSOR  FIRST STEP 

In [5]:
x= tf.constant(4,shape=(2,3),dtype=tf.float32)

In [6]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

In [7]:
x=tf.zeros((2,3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [8]:
x=tf.ones((2,3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
x=tf.eye(2)  # eye is used for identify matrix 
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [14]:
x= tf.random.normal((3,3),mean=0,stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.9033892 ,  2.0566638 , -2.7493322 ],
       [-1.067031  ,  0.49638015, -0.8526989 ],
       [-0.6187241 ,  0.89391345,  0.18837593]], dtype=float32)>

In [15]:
x= tf.random.uniform((3,3),minval=0,maxval=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.9877902 , 0.10213888, 0.3729247 ],
       [0.38087785, 0.7336527 , 0.60821366],
       [0.93814015, 0.9663229 , 0.17252827]], dtype=float32)>

In [24]:
x=tf.range(start=1,limit=10,delta=2)
x = tf.cast(x,dtype=tf.float32)

In [25]:
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 3., 5., 7., 9.], dtype=float32)>

MATHEMATICAL OPEARTION   SECOND STEP

In [26]:
x=tf.constant([1,3,7])
y=tf.constant([3,5,9])

In [29]:
z=tf.add(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 16])>

In [33]:
z = tf.tensordot(x,y,axes=1)
z

<tf.Tensor: shape=(), dtype=int32, numpy=81>

In [40]:
x=tf.random.normal((2,4))
y=tf.random.normal((4,7))

z=tf.matmul(x,y) #first way

z = x @ y #second way
z

<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[-1.121585  ,  1.3065987 ,  3.0599165 ,  1.4946877 , -0.86113274,
        -0.01629472,  2.1200602 ],
       [ 2.0308573 , -4.4877663 , -1.1145797 , -3.667304  ,  3.8611772 ,
        -2.5814908 ,  1.3787773 ]], dtype=float32)>

INDEXING      3RD STEP

In [45]:
x=tf.constant([1,3,7,5,6,8,9,2])
print(x[::3])  # for skiping
(x[::-1])  #for reverse

tf.Tensor([1 5 9], shape=(3,), dtype=int32)


<tf.Tensor: shape=(8,), dtype=int32, numpy=array([2, 9, 8, 6, 5, 7, 3, 1])>

RESHAPING    STEP 4

In [46]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [48]:
x = tf.reshape(x,(3,3))
x


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>